/* Copyright (c) 2026 James Honiball (KC3TFZ)
 *
 * This file is part of VUURWERK and is dual-licensed:
 *   1. GPL v3 (when distributed as part of the VUURWERK firmware)
 *   2. Commercial license available from the author
 *
 * You may not extract, repackage, or redistribute this file
 * independently under any license other than GPL v3 as part
 * of the complete VUURWERK firmware, without written permission
 * from the author.
 *
 * Commercial licensing inquiries: jhoniball4@gmail.com
 */

#include <stdint.h>

#include "ctcss_lead.h"
#include "driver/bk4819.h"
#include "radio.h"

#define TONE_LEAD_TICKS 15   // 150ms at 10ms/tick

// 0 = inactive; >0 = ticks remaining (10ms each).
// BSS zero-init at boot covers the inactive default.
static uint8_t s_countdown;

void CTCSS_LEAD_Start(void)
{
	// Only use tone lead if channel has CTCSS or DCS enabled
	if (gCurrentVfo->pTX->CodeType == CODE_TYPE_OFF) {
		s_countdown = 0;
		return;
	}

	// Mute mic audio -- CTCSS tone still transmits (generated by BK4819 hardware)
	BK4819_EnterTxMute();
	s_countdown = TONE_LEAD_TICKS;
}

void CTCSS_LEAD_Process(void)
{
	if (s_countdown == 0)
		return;

	if (--s_countdown == 0) {
		// Tone lead period complete -- unmute mic audio
		BK4819_ExitTxMute();
	}
}

void CTCSS_LEAD_Stop(void)
{
	if (s_countdown != 0) {
		// PTT released before lead-in finished -- ensure mic is unmuted
		BK4819_ExitTxMute();
		s_countdown = 0;
	}
}
